
import React from 'react';
import { PenTool, Mic, BarChart3, Palette, FileEdit, Globe, Layers, BookOpen, Users, GraduationCap, Library } from 'lucide-react';
import { Project, Service, BlogPost } from './types';

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'The Algorithm of Empathy',
    excerpt: 'Exploring how we can teach language models to understand nuance, tone, and the unspoken weight of human emotion.',
    date: 'Feb 4, 2026',
    readTime: '5 min read',
    imageUrl: 'https://picsum.photos/seed/blog1/800/600',
    tags: ['Technology', 'Philosophy', 'Writing'],
    content: `The digital landscape is currently flooded with a specific kind of language: perfectly structured, entirely polite, and completely hollow. As brands rush to adopt the latest language models to scale their output, they are discovering a critical flaw in the machinery. Technology can easily mimic vocabulary, but it struggles to replicate a pulse.

This is the frontier of modern narrative strategy. The goal is no longer just generation; it is translation.

Empathy cannot be coded through standard prompts. It requires an architectural approach to language. Teaching a model to understand the unspoken weight of human emotion means feeding it context, not just commands. It involves training the technology to recognize the subtle difference between confidence and arrogance, or the delicate space between empathy and pity.

For over a decade and a half, the core of effective marketing operations has remained the same: human connection. When I structure a brand's digital voice, the technology acts merely as the high-speed loom. The Studio remains the weaver. By meticulously curating the inputs—injecting literary texture, historical context, and psychological depth—we can teach these models to operate with a degree of digital empathy.

The brands that win the next decade will not be the ones that generate the most content. They will be the ones that train their technology to feel.`
  },
  {
    id: '2',
    title: 'Mid-Century Modernism in the Digital Age',
    excerpt: 'Why the clean lines and functional beauty of 1950s design are more relevant than ever in our cluttered digital interfaces.',
    date: 'Jan 28, 2024',
    readTime: '4 min read',
    imageUrl: 'https://picsum.photos/seed/blog2/800/600',
    tags: ['Design', 'Aesthetics', 'Culture']
  },
  {
    id: '3',
    title: 'Silence as a Strategy',
    excerpt: 'In a world of constant noise, the most powerful brand move might be knowing when to stay quiet.',
    date: 'Jan 15, 2024',
    readTime: '6 min read',
    imageUrl: 'https://picsum.photos/seed/blog3/800/600',
    tags: ['Strategy', 'Branding', 'Minimalism']
  }
];

export const SERVICES: Service[] = [
  {
    id: 'consultancy',
    title: 'Strategic Consultancy',
    description: 'Bridging the gap between human creativity and technological efficiency. The Studio trains language models to understand nuance and context, ensuring a brand\'s voice scales with absolute precision while remaining authentically yours.',
    icon: <Globe className="w-6 h-6" />,
    tagline: 'The Blueprint',
  },
  {
    id: 'writing',
    title: 'Bespoke Narrative',
    description: 'Long-form journalism, technical copy, and storytelling that breathes life into the digital void. In an age of AI-Generated content, The Studio engineers language that commands attention and connects on a visceral level.',
    icon: <PenTool className="w-6 h-6" />,
    tagline: 'The Voice',
  },
  {
    id: 'broadcast',
    title: 'The Broadcast',
    description: 'The intimacy of the human voice meets the power of visual storytelling. Full-cycle multimedia production for podcasts, social video, brand films, and digital campaigns that demand to be seen.',
    icon: <Mic className="w-6 h-6" />,
    tagline: 'The Signal',
  },
  {
    id: 'library',
    title: 'The Library',
    description: 'Curated industry knowledge distilled into elegant digital formats. eBooks, toolkits, and authoritative resources designed to educate your audience, inspire action, and establish unshakeable authority.',
    icon: <BookOpen className="w-6 h-6" />,
    tagline: 'The Knowledge',
  },
  {
    id: 'speaking',
    title: 'The Podium',
    description: 'Corporate workshops and public speaking on the synthesis of art and algorithm. Master how to harness the speed of technology while fiercely maintaining the human soul in the machine age.',
    icon: <Users className="w-6 h-6" />,
    tagline: 'The Stage',
  },
  {
    id: 'english',
    title: 'The Lexicon',
    description: 'Advanced communication and English coaching for professionals. We refine your narrative delivery to be as precise as it is persuasive, ensuring nothing is lost in translation.',
    icon: <GraduationCap className="w-6 h-6" />,
    tagline: 'The Craft',
  },
  {
    id: 'studio88',
    title: 'Studio88 Design',
    description: 'Visual systems and brand identity that marry mid-century form with modern function. Web experiences that feel meticulously crafted by human hands, not just coded by machines.',
    icon: <Layers className="w-6 h-6" />,
    tagline: 'The Visual',
  },
  {
    id: 'marketing',
    title: 'Growth Architecture',
    description: 'Data-driven marketing campaigns that build genuine community. We leverage technology to find your exact audience, and human empathy to keep them fiercely loyal.',
    icon: <BarChart3 className="w-6 h-6" />,
    tagline: 'The Engine',
  },
];

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Animation Industry Trends',
    category: 'Writing',
    description: 'Deep dive into the evolving landscape of animation technology and storytelling.',
    imageUrl: 'https://i.ibb.co/yHFbsD7/1-2.png',
    client: 'Business of Animation',
    projectType: 'Industry Analysis',
    link: 'https://businessofanimation.com/new-animation-trends-animators-need-to-try/',
  },
  {
    id: '1b',
    title: 'The Remote Studio',
    category: 'Writing',
    description: 'Strategies for building a world-class animation workspace from anywhere.',
    imageUrl: 'https://i.ibb.co/Lh9f5w3V/2-2.png',
    client: 'Business of Animation',
    projectType: 'Professional Guide',
    link: 'https://businessofanimation.com/creating-a-conducive-animator-work-environment-anywhere/',
  },
  {
    id: '1c',
    title: 'Sourcing Inspiration',
    category: 'Writing',
    description: 'A methodology for finding creative sparks in the mundane.',
    imageUrl: 'https://i.ibb.co/3YGzZDcr/3-2.png',
    client: 'Business of Animation',
    projectType: 'Creative Strategy',
    link: 'https://businessofanimation.com/how-to-look-for-animation-inspiration-for-animators/',
  },
  {
    id: '1d',
    title: 'The Freelance Animator',
    category: 'Writing',
    description: 'Navigating the business side of creativity with professional insights.',
    imageUrl: 'https://i.ibb.co/HT93bXsT/4.png',
    client: 'Business of Animation',
    projectType: 'Career Development',
    link: 'https://businessofanimation.com/freelance-animation-tips-from-professionals/',
  },
  {
    id: 'social-branding-video',
    title: 'Social Branding Video',
    category: 'Video',
    description: 'Engaging social media video content for brand identity.',
    imageUrl: 'https://i.ibb.co/gMQrzJzC/5.png',
    client: 'Sydie Media',
    projectType: 'Social Video',
    link: 'https://www.facebook.com/share/v/1DnvaqUc8P/',
  },
  {
    id: 'canmar-wefunder',
    title: 'CanMar Wefunder Campaign',
    category: 'Marketing',
    description: 'Strategic crowdfunding campaign for CanMar.',
    imageUrl: 'https://i.ibb.co/JRmGQm29/6.png',
    client: 'CanMar',
    projectType: 'Crowdfunding',
    link: 'https://wefunder.com/canmarofficial',
  },
  {
    id: 'canmar-app',
    title: 'CanMar Community App',
    category: 'Design',
    description: 'Full app branding, UI/UX design, and production for the alternative wellness community platform.',
    imageUrl: 'https://i.ibb.co/Sw8KDBWk/7.png',
    client: 'CanMar',
    projectType: 'App Design & UI/UX',
    link: 'https://community.canmar.io/signup',
  },
  {
    id: 'canmar-talkshow',
    title: 'CanMar Morning Talk Show',
    category: 'Video',
    description: 'A multi-season talk show series featuring industry leaders and insights.',
    imageUrl: 'https://i.ibb.co/Jw65d1Zq/8.png',
    client: 'CanMar',
    projectType: 'Talk Show Series',
    modalType: 'seasons',
    seasonLinks: [
      { season: 'Season 1', url: 'https://youtube.com/playlist?list=PLoAmnZNbEraj_shjuW48CRHmH2nsEZjpy&si=gel9Ermnm3FLH39E' },
      { season: 'Season 2', url: 'https://youtube.com/playlist?list=PLoAmnZNbEragkVI5WqgbP1OfYDSKsklx6&si=lR6R-wjiOBH1pPM1' },
      { season: 'Season 3', url: 'https://youtube.com/playlist?list=PLoAmnZNbEraiTr4AuSbf3of9gLmxzlm2S&si=Rngi8ozBQYyyHekg' },
    ],
  },
  {
    id: 'canmar-youtube',
    title: 'CanMar YouTube Channel',
    category: 'Marketing',
    description: 'Hosting, marketing, and content strategy for CanMar\'s video presence.',
    imageUrl: 'https://i.ibb.co/qLPZNL8z/9.png',
    client: 'CanMar',
    projectType: 'Channel Management',
    link: 'https://youtube.com/@canmarofficial?si=DdP5lBk9cRNdZK8j',
  },
  {
    id: 'canmar-investor-video',
    title: 'CanMar Investor Pitch',
    category: 'Video',
    description: 'Compelling investor-focused video content for fundraising.',
    imageUrl: 'https://i.ibb.co/S4Zvmtfr/10.png',
    client: 'CanMar',
    projectType: 'Investor Video',
    link: 'https://youtu.be/qtM-xmuTN9M?si=RhqUrnVt5IMGLjR_',
  },
  {
    id: 'canmar-podcast',
    title: 'CanMar Morning Talk Show podcast',
    category: 'Audio',
    description: 'Audio production and engineering for the CanMar podcast series.',
    imageUrl: 'https://i.ibb.co/Cx1gLqR/11.png',
    client: 'CanMar',
    projectType: 'Podcast Production',
    link: 'https://open.spotify.com/show/5klzp895l6NsxYIUdgxzDy?si=El00yMj6QomwSEsh1MrYYA',
  },
  {
    id: 'canmar-linktree',
    title: 'CanMar Digital Hub',
    category: 'Marketing',
    description: 'Centralized digital presence management via Linktree.',
    imageUrl: 'https://i.ibb.co/4LPNMKk/12.png',
    client: 'CanMar',
    projectType: 'Digital Strategy',
    link: 'https://linktr.ee/canmarofficial?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAb21jcAQTcGFleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA81NjcwNjczNDMzNTI0MjcAAadyCX9EOFaMPL80Gf3CSC9n3oWqhRF45VDdasGfq3yP6E7A5wwepXYyVaXEgg_aem_uvT2g9FhU1EMEeaOjGCGjw',
  },
  {
    id: 'canmar-social',
    title: 'CanMar Social Ecosystem',
    category: 'Marketing',
    description: 'Comprehensive social media strategy and community engagement across platforms.',
    imageUrl: 'https://i.ibb.co/4ZxSRpCP/13.png',
    client: 'CanMar',
    projectType: 'Social Media',
    modalType: 'social',
    socialLinks: [
      { platform: 'Facebook', url: 'https://www.facebook.com/share/1C6enhCbJC/' },
      { platform: 'Instagram', url: 'https://www.instagram.com/canmarofficial?igsh=MWp2ODlnenU0d2lvcQ==' },
      { platform: 'LinkedIn', url: 'https://www.linkedin.com/company/canmarofficial/' },
    ],
  },
  {
    id: 'canmar-mediakit',
    title: 'CanMar Media Kit',
    category: 'Design',
    description: 'Professional media kit design for partnership outreach.',
    imageUrl: 'https://i.ibb.co/WNkpWZmt/14.png',
    client: 'CanMar',
    projectType: 'Collateral Design',
    link: 'https://tr.ee/89qIe37lPe',
  },
  {
    id: 'canmar-video-prod',
    title: 'CanMar Video Production',
    category: 'Video',
    description: 'High-quality video production for brand storytelling.',
    imageUrl: 'https://i.ibb.co/SDhVQzQT/15.png',
    client: 'CanMar',
    projectType: 'Video Production',
    link: 'https://youtu.be/aklM-AHaASY?si=mRcqom02ja_gStQa',
  },
  {
    id: 'canmar-article-1',
    title: 'Member Spotlight: Megan Hollingsworth',
    category: 'Writing',
    description: 'In-depth interview and profile piece on industry leader Megan Hollingsworth.',
    imageUrl: 'https://i.ibb.co/ymK7R4KL/16.png',
    client: 'CanMar',
    projectType: 'Feature Article',
    modalType: 'gated',
    platformName: 'CanMar',
    excerpt: 'An exclusive look into the journey of Megan Hollingsworth, PHARMD, and her impact on the medical cannabis landscape through Mindful Medix.',
    link: 'https://community.canmar.io/articles/387',
  },
  {
    id: 'canmar-article-2',
    title: 'Is Cannabis Legal in South Africa?',
    category: 'Writing',
    description: 'Comprehensive analysis of the legal landscape of cannabis in South Africa.',
    imageUrl: 'https://i.ibb.co/tMgTVYk1/17.png',
    client: 'CanMar',
    projectType: 'Legal Analysis',
    modalType: 'gated',
    platformName: 'CanMar',
    excerpt: 'Navigating the complexities of cannabis legislation in South Africa: It’s a bit more complicated than a simple yes or no.',
    link: 'https://community.canmar.io/articles/349',
  },
  {
    id: 'canmar-article-3',
    title: 'The Road to Psychedelics Legalization',
    category: 'Writing',
    description: 'Investigative piece on the evolving legal status of psychedelics.',
    imageUrl: 'https://i.ibb.co/pv7kjScW/18.png',
    client: 'CanMar',
    projectType: 'Investigative Journalism',
    modalType: 'gated',
    platformName: 'CanMar',
    excerpt: 'Tracing the long and winding road towards the legalization of psychedelics and what it means for the future of medicine.',
    link: 'https://community.canmar.io/articles/372',
  },
  {
    id: 'dest-videos',
    title: 'DestinationOne social reel',
    category: 'Video',
    description: 'Corporate video content highlighting leadership and honesty in recruitment.',
    imageUrl: 'https://i.ibb.co/mC1X37Wx/19.png',
    client: 'DestinationOne',
    projectType: 'Corporate Video',
    link: 'https://www.linkedin.com/posts/destinationoneconsulting_leadership-honesty-recruitment-activity-7430280322438615040-Yoio?utm_source=share&utm_medium=member_android&rcm=ACoAABercywBd7L_7ni0ViWWYd8SD50veILNIg0',
  },
  {
    id: 'dest-social',
    title: 'DestinationOne Social Ecosystem',
    category: 'Marketing',
    description: 'Strategic social media management for a leading recruitment firm.',
    imageUrl: 'https://i.ibb.co/xtcqHkH0/20.png',
    client: 'DestinationOne',
    projectType: 'Social Media',
    modalType: 'social',
    socialLinks: [
      { platform: 'LinkedIn', url: 'https://www.linkedin.com/company/destinationoneconsulting/' },
      { platform: 'Facebook', url: 'https://www.facebook.com/destinationoneConsultingInc?http_ref=eyJ0cyI6IjE3NzI1MjIwMDA5MDciLCJyIjoiaHR0cHM6XC9cL2Rlc3RpbmF0aW9ub25lLmNhXC8ifQ%3D%3D&cah=2&rwtsid=2ytGcrKZYfIMrQMGG' },
      { platform: 'Instagram', url: 'https://www.instagram.com/destinationoneconsulting?igsh=MWJrZ2p0OHkxMjQzNg==' },
    ],
  },
  {
    id: 'dest-copy',
    title: 'DestinationOne Website Copy',
    category: 'Writing',
    description: 'Compelling web copy articulating the firm\'s value proposition and services.',
    imageUrl: 'https://i.ibb.co/MD1vr47n/21.png',
    client: 'DestinationOne',
    projectType: 'Website Copy',
    link: 'https://destinationone.ca/',
  },
  {
    id: 'lmon-article-1',
    title: 'How to Help Kids Borrow Your Calm-Without Burning Out Yourself',
    category: 'Writing',
    description: 'When kids are overwhelmed, they often reach for our steadiness to steady themselves. But what happens when we’re stretched too thin?',
    imageUrl: 'https://i.ibb.co/CfdghyR/31-20260309-224116-0004.png',
    client: 'LMON',
    projectType: 'Exclusive Article',
    modalType: 'gated',
    platformName: 'LMON',
    excerpt: 'Deep dive into emerging market trends and strategic opportunities within the sector.',
    link: 'https://app.lmon.com/articles/728',
  },
  {
    id: 'lmon-article-2',
    title: 'Separation Anxiety in Pets: How to Spot It and Support Them',
    category: 'Writing',
    description: 'Strategic briefing for industry professionals.',
    imageUrl: 'https://i.ibb.co/6Rhytbpw/32-20260309-224116-0005.png',
    client: 'LMON',
    projectType: 'Exclusive Article',
    modalType: 'gated',
    platformName: 'LMON',
    excerpt: 'Key takeaways and actionable insights for navigating the current business landscape.',
    link: 'https://app.lmon.com/articles/95',
  },
  {
    id: 'lmon-article-3',
    title: 'Not a Math Person? Try a Values-Based Budget',
    category: 'Writing',
    description: 'Tired of budgeting spreadsheets that feel like algebra class? A values-based budget offers another route-one where your money reflects what matters most.',
    imageUrl: 'https://i.ibb.co/PGXmMLR9/33-20260309-224116-0006.png',
    client: 'LMON',
    projectType: 'Exclusive Article',
    modalType: 'gated',
    platformName: 'LMON',
    excerpt: 'Exploring the frontiers of innovation and the leaders driving change.',
    link: 'https://app.lmon.com/articles/653',
  },
  {
    id: 'lmon-audio-1',
    title: 'Audio: Out of Sight, Still on Mind: ADHD, Object Permanence, and Workflows',
    category: 'Audio',
    description: 'When items go out of sight, they often go out of mind - especially for someone with ADHD. This article explains how the brain’s object permanence system works differently for many neurodivergent folks, and then offers smart, compassionate supports (visual cues, tech tools, environment design) to help everyday memory and workflow feel less like holding sand and more like building scaffolding',
    imageUrl: 'https://i.ibb.co/NdSzd24t/34-20260309-224116-0007.png',
    client: 'LMON',
    projectType: 'Audio Feature',
    modalType: 'gated',
    platformName: 'LMON',
    excerpt: 'Listen to expert analysis on current market dynamics and future projections.',
    link: 'https://app.lmon.com/articles/643',
  },
  {
    id: 'lmon-audio-2',
    title: 'Audio: Menopause & Movement: Supporting Hormones Through Exercise',
    category: 'Audio',
    description: 'Hormones may fluctuate, but your ability to feel strong, supported, and steady in your body doesn’t have to. This guide offers movement strategies that help you feel more in control during perimenopause and beyond while honoring the very real shifts happening underneath it all.',
    imageUrl: 'https://i.ibb.co/tM93vCJC/35-20260309-224116-0008.png',
    client: 'LMON',
    projectType: 'Audio Feature',
    modalType: 'gated',
    platformName: 'LMON',
    excerpt: 'Candid conversations with the movers and shakers of the industry.',
    link: 'https://app.lmon.com/articles/660',
  },
  {
    id: 'lmon-audio-3',
    title: 'Audio: Your Gut\'s SOS Signals: What Bloating Is Really Saying',
    category: 'Audio',
    description: 'Bloating isn\'t just annoying; it\'s your gut trying to tell you something. This article decodes what those belly puffs actually mean, explores common causes (from stress to sneaky food triggers), and offers practical steps to help you feel lighter and more in tune with your gut.',
    imageUrl: 'https://i.ibb.co/5XjD80kn/36-20260309-224116-0009.png',
    client: 'LMON',
    projectType: 'Audio Feature',
    modalType: 'gated',
    platformName: 'LMON',
    excerpt: 'Unpacking strategies for sustainable growth and scalability in a competitive market.',
    link: 'https://app.lmon.com/articles/691',
  },
  {
    id: 'lmon-app',
    title: 'LMON App Experience',
    category: 'Design',
    description: 'User-centric app design and development for LMON.',
    imageUrl: 'https://i.ibb.co/38266qn/37-20260309-224116-0010.png',
    client: 'LMON',
    projectType: 'App Design',
    link: 'https://app.lmon.com/signup/qEsfZR',
  },
  {
    id: 'lmon-social',
    title: 'LMON social ecosystem',
    category: 'Marketing',
    description: 'Building a vibrant online community for LMON users.',
    imageUrl: 'https://i.ibb.co/cKtPksJZ/20260309-225429-0000.png',
    client: 'LMON',
    projectType: 'Social Media',
    modalType: 'social',
    socialLinks: [
      { platform: 'Facebook', url: 'https://www.facebook.com/share/1Myk56izRn/' },
      { platform: 'Instagram', url: 'https://www.instagram.com/lmonapp?igsh=MWNxMGU4dm5pZjZkcg==' },
      { platform: 'LinkedIn', url: 'https://www.linkedin.com/company/lmon/' },
    ],
  },
  {
    id: 'lmon-web',
    title: 'LMON Website Copy',
    category: 'Writing',
    description: 'Clear, concise, and converting website copy for LMON.',
    imageUrl: 'https://i.ibb.co/pjJ7rY3C/20260309-225430-0001.png',
    client: 'LMON',
    projectType: 'Website Copy',
    link: 'https://lmon.com/',
  },
  {
    id: 'eddie-social',
    title: 'Eddie Macs @ VP Social',
    category: 'Marketing',
    description: 'Social media engagement for Eddie Macs at VP.',
    imageUrl: 'https://i.ibb.co/VYzSjFMx/24.png',
    client: 'Eddie Macs @ VP',
    projectType: 'Social Media',
    modalType: 'social',
    socialLinks: [
      { platform: 'Facebook', url: 'https://www.facebook.com/share/1XEuEGYDsQ/' },
    ],
  },
  {
    id: 'eddie-web',
    title: 'Eddie Macs Website',
    category: 'Design',
    description: 'Website design and development for Eddie Macs @ VP.',
    imageUrl: 'https://i.ibb.co/B2kPCpNc/23.png',
    client: 'Eddie Macs @ VP',
    projectType: 'Website Design',
    link: 'https://www.eddiemacsatvp.com/',
  },
  {
    id: 'music-posters',
    title: 'Music Posters Collection',
    category: 'Design',
    description: 'A curated collection of music poster designs showcasing visual rhythm and typographic harmony.',
    imageUrl: 'https://i.ibb.co/RTQkj0R0/8-20250720-192837-0007.png',
    client: 'Various Artists',
    projectType: 'Graphic Design',
    modalType: 'gallery',
    galleryImages: [
      'https://i.ibb.co/RTQkj0R0/8-20250720-192837-0007.png',
      'https://i.ibb.co/DP1298MG/5-20250720-192837-0004.png',
      'https://i.ibb.co/HLJR00tp/3-20260210-154341-0002.png',
      'https://i.ibb.co/FbJYWmMT/FB-IMG-1772527365160.jpg',
      'https://i.ibb.co/C3ywk8Yy/FB-IMG-1772527304469.jpg',
      'https://i.ibb.co/tPX8nJ3F/FB-IMG-1772527399128.jpg',
      'https://i.ibb.co/mfBP81H/FB-IMG-1772527582072.jpg',
      'https://i.ibb.co/MkR3xjwv/FB-IMG-1772527622273.jpg',
      'https://i.ibb.co/gZcmtWjJ/FB-IMG-1772527611320.jpg'
    ]
  },
  {
    id: 'marketing-designs',
    title: 'Marketing & Branding Collection',
    category: 'Design',
    description: 'Strategic marketing collateral and comprehensive branding systems, including logos, social media assets, and visual identity guidelines.',
    imageUrl: 'https://i.ibb.co/xZr7fbJ/marketing-1.png',
    client: 'Various Clients',
    projectType: 'Marketing & Branding',
    modalType: 'gallery',
    galleryImages: [
      'https://i.ibb.co/xZr7fbJ/marketing-1.png',
      'https://i.ibb.co/CK22pkW8/marketing-2.png',
      'https://i.ibb.co/GDCHJ57/marketing-3.png',
      'https://i.ibb.co/3mxvm06q/marketing-4.png',
      'https://i.ibb.co/7dff88jD/marketing-5.png',
      'https://i.ibb.co/KprPpCgW/marketing-6.png',
      'https://i.ibb.co/vCFgQb8t/marketing-7.png',
      'https://i.ibb.co/dHs4tJf/marketing-8.png',
      'https://i.ibb.co/LDxQyCCn/marketing-9.png',
      'https://i.ibb.co/CKqyt96S/marketing-10.png',
      'https://i.ibb.co/Z6swC1yp/marketing-11.png',
      'https://i.ibb.co/7tGNx6M4/marketing-12.png',
      'https://i.ibb.co/7xHSPB1L/marketing-13.png',
      'https://i.ibb.co/gFw8S522/marketing-14.png'
    ],
    carouselPostImages: [
      'https://ibb.co/GQf99Wnn',
      'https://ibb.co/tTrBQqdM',
      'https://ibb.co/Dfmpvpmg',
      'https://ibb.co/SDGQq4b4',
      'https://ibb.co/twQfCfrk',
      'https://ibb.co/fzw6j3X6'
    ]
  },
  {
    id: 'tech-art-collection',
    title: 'Custom Generative Collection',
    category: 'Design',
    description: 'Breathing humanity into generative technology. Utilizing custom models to create bespoke, on-brand artwork that bridges the gap between digital precision and organic expression.',
    imageUrl: 'https://i.ibb.co/yB0sFCwC/20260223-160554-0000.png',
    client: 'Various Clients',
    projectType: 'Generative Art',
    modalType: 'gallery',
    galleryImages: [
      'https://i.ibb.co/yB0sFCwC/20260223-160554-0000.png',
      'https://i.ibb.co/Vp9Ks6qZ/20260223-160554-0001.png',
      'https://i.ibb.co/PGkxQv2S/20260223-160554-0002.png',
      'https://i.ibb.co/ccwdTFhr/Untitled-Linked-In-Post-20260216-162811-0001.png',
      'https://i.ibb.co/svbDG7qC/Untitled-Linked-In-Post-20260209-164838-0001.png',
      'https://i.ibb.co/Xrwpz99K/Untitled-Linked-In-Post-20260209-164839-0002.png',
      'https://i.ibb.co/4Z3zykRX/Untitled-Linked-In-Post-20260204-094346-0001.png',
      'https://i.ibb.co/8DdR4ynr/20260203-153416-0000.png',
      'https://i.ibb.co/0ygKSDHX/20260128-121726-0000.png',
      'https://i.ibb.co/gb99sgBJ/20260128-121726-0001.png',
      'https://i.ibb.co/cKmZBLxS/20260128-121726-0002.png',
      'https://i.ibb.co/xth1RDN3/Untitled-Linked-In-Post-20260123-171015-0000.png',
      'https://i.ibb.co/67yXjJRC/Untitled-Linked-In-Post-20260123-172845-0000.png'
    ]
  },
];